name: CI Pipeline
on:
    push:
        branches:
          - main
   
    pull_request:
      branches: 
        - main
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              id: checkout-code
              uses: actions/checkout@v4
            
            - name: Setup Python
              id: setup-python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Setup Poetry
              id: setup-poetry
              uses: abatilo/actions-poetry@v4
            
            - name: Install Dependencies
              id: install-dependencies
              run: poetry install
            
            - name: Lint Python Code
              id: lint-code
              run: poetry run ruff check src tests